version: "1.0"
info:
  model: int-scaffold
packages:
- name: ICUI_AutomationProject0619Project
  gitServerName: ICAccount0619
  gitUrl: https://github.com/amlanbhowmick85/ICUI_AutomationProject0619Project
  gitUsername: amlanbhowmick85
  gitBranch: main
